# CMake generated Testfile for 
# Source directory: /home/jaeger/lsquic-fork/test/unittests
# Build directory: /home/jaeger/lsquic-fork/test/unittests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(rechist "test_rechist")
add_test(senhist "test_senhist")
add_test(rtt "test_rtt")
add_test(set "test_set")
add_test(engine_ctor "test_engine_ctor")
add_test(stream "test_stream")
add_test(stream_hash "test_stream" "-h")
add_test(stream_A "test_stream" "-A")
add_test(stream_hash_A "test_stream" "-A" "-h")
add_test(spi "test_spi")
add_test(malo "test_malo")
add_test(conn_hash "test_conn_hash")
add_test(lsquic_hash "test_lsquic_hash")
add_test(blocked_gquic_le "test_blocked_gquic_le")
add_test(blocked_gquic_be "test_blocked_gquic_be")
add_test(rst_stream_gquic_le "test_rst_stream_gquic_le")
add_test(rst_stream_gquic_be "test_rst_stream_gquic_be")
add_test(conn_close_gquic_le "test_conn_close_gquic_le")
add_test(conn_close_gquic_be "test_conn_close_gquic_be")
add_test(goaway_gquic_le "test_goaway_gquic_le")
add_test(goaway_gquic_be "test_goaway_gquic_be")
add_test(wuf_gquic_le "test_wuf_gquic_le")
add_test(wuf_gquic_be "test_wuf_gquic_be")
add_test(ackparse_gquic_le "test_ackparse_gquic_le")
add_test(ackparse_gquic_be "test_ackparse_gquic_be")
add_test(ackgen_gquic_le "test_ackgen_gquic_le")
add_test(ackgen_gquic_be "test_ackgen_gquic_be")
add_test(sfcw "test_sfcw")
add_test(alarmset "test_alarmset")
add_test(streamparse "test_streamparse")
add_test(packet_out "test_packet_out")
add_test(reg_pkt_headergen "test_reg_pkt_headergen")
add_test(ver_nego "test_ver_nego")
add_test(packno_len "test_packno_len")
add_test(streamgen "test_streamgen")
add_test(some_packets "test_some_packets")
add_test(elision "test_elision")
add_test(stop_waiting_gquic_le "test_stop_waiting_gquic_le")
add_test(stop_waiting_gquic_be "test_stop_waiting_gquic_be")
add_test(parse_packet_in "test_parse_packet_in")
add_test(quic_le_floats "test_quic_le_floats")
add_test(quic_be_floats "test_quic_be_floats")
add_test(export_key "test_export_key")
add_test(frame_reader "test_frame_reader")
add_test(frame_writer "test_frame_writer")
add_test(frame_chop "test_frame_chop")
add_test(frame_rw "test_frame_rw")
add_test(hkdf "test_hkdf")
add_test(attq "test_attq")
add_test(arr "test_arr")
add_test(buf "test_buf")
add_test(cubic "test_cubic")
